// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/login": {
            "post": {
                "description": "Autenticar um usuário com login e senha",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "Autenticar um usuário",
                "parameters": [
                    {
                        "description": "Credenciais do usuário",
                        "name": "credentials",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handlers.LoginDTO"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handlers.AuthResponse"
                        }
                    }
                }
            }
        },
        "/register": {
            "post": {
                "description": "Crie um novo usuário fornecendo o nome de usuário, login e senha",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "Criar um novo usuário",
                "parameters": [
                    {
                        "description": "Registro de usuário",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handlers.RegisterDTO"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/models.User"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "handlers.AuthResponse": {
            "description": "DTO para resposta de autenticação",
            "type": "object",
            "properties": {
                "autenticado": {
                    "type": "boolean"
                },
                "dataHoraExpiracao": {
                    "type": "string"
                },
                "token": {
                    "type": "string"
                },
                "usuarioLogin": {
                    "type": "string"
                },
                "usuarioNome": {
                    "type": "string"
                }
            }
        },
        "handlers.LoginDTO": {
            "description": "DTO para login do usuário",
            "type": "object",
            "properties": {
                "senha": {
                    "type": "string"
                },
                "usuarioLogin": {
                    "type": "string"
                }
            }
        },
        "handlers.RegisterDTO": {
            "description": "DTO para registro de usuário",
            "type": "object",
            "properties": {
                "senha": {
                    "type": "string"
                },
                "usuarioLogin": {
                    "type": "string"
                },
                "usuarioNome": {
                    "type": "string"
                }
            }
        },
        "models.User": {
            "description": "Modelo de usuário com campos GORM",
            "type": "object",
            "properties": {
                "id": {
                    "description": "@Description O identificador exclusivo do usuário",
                    "type": "integer"
                },
                "senha": {
                    "description": "@Description Senha do usuário",
                    "type": "string"
                },
                "usuarioLogin": {
                    "description": "@Description Login do usuário",
                    "type": "string"
                },
                "usuarioNome": {
                    "description": "@Description Nome completo do usuário",
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
