definitions:
  handlers.AuthResponse:
    description: DTO para resposta de autenticação
    properties:
      autenticado:
        type: boolean
      dataHoraExpiracao:
        type: string
      token:
        type: string
      usuarioLogin:
        type: string
      usuarioNome:
        type: string
    type: object
  handlers.LoginDTO:
    description: DTO para login do usuário
    properties:
      senha:
        type: string
      usuarioLogin:
        type: string
    type: object
  handlers.RegisterDTO:
    description: DTO para registro de usuário
    properties:
      senha:
        type: string
      usuarioLogin:
        type: string
      usuarioNome:
        type: string
    type: object
  models.User:
    description: Modelo de usuário com campos GORM
    properties:
      id:
        description: '@Description O identificador exclusivo do usuário'
        type: integer
      senha:
        description: '@Description Senha do usuário'
        type: string
      usuarioLogin:
        description: '@Description Login do usuário'
        type: string
      usuarioNome:
        description: '@Description Nome completo do usuário'
        type: string
    type: object
info:
  contact: {}
paths:
  /login:
    post:
      consumes:
      - application/json
      description: Autenticar um usuário com login e senha
      parameters:
      - description: Credenciais do usuário
        in: body
        name: credentials
        required: true
        schema:
          $ref: '#/definitions/handlers.LoginDTO'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handlers.AuthResponse'
      summary: Autenticar um usuário
  /register:
    post:
      consumes:
      - application/json
      description: Crie um novo usuário fornecendo o nome de usuário, login e senha
      parameters:
      - description: Registro de usuário
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/handlers.RegisterDTO'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/models.User'
      summary: Criar um novo usuário
swagger: "2.0"
